language: node_js
node_js:
  - "0.12"
deploy:
  provider: heroku
  api_key:
    secure: cs2PYuIXYPpZG0UKAEJXWN9YU5lRDDmQxH2BEQld9htBtzFtNdk2fXmVBD0XNlm0bjgIBQJN0RevECxQoygbHJIoLRKyl/3ZL0UiyOR93KX98TzyYiOfuiZ+VyEXm0QZ2fDM6Y7EPea3u3FQb85s4k1r0Oz2j89yC/h39lFCshHkrSgP+BrcAvI8CjwbM92EU2xl18AV7bx+tcl6c4eRkvliszzEn9ftAiuCJmeG9OfuCGAkYTkh8bfhKW7+KLScv31p39eSAn8Ipwp6sJLIMKbbdA/M1T8CIMO+ztjRgc+sCSPABbE9zS6ZkAJcLjccgu3PTt6q4GFvLUEAxVPo9ZAyjQ3LrNR2f+2KuybL6gyFPD9aotNaD/6gfy7INiplEClVsdINT78aBQseGerQTQM+sz+9391xhNQEN5px5lANvYwC4VLXmFD4blmO2xwz11LH4IeM5XR6W6h9zi2eUQU6vApSm8YkzWhBWC0Fflyf65HlzaWqTQdiwrd+JRX1wtHMHvaledOYSQqakoh+oP3LoSuTpcOv+ojdebrqt+WsKVEM2uHG1pH+bmynRzSFMpRt9ktjFuNHgRLffhrtZ7xnVzj2gPmLGe9OxbhFLBDtn863Q8xfTO4Xlq0h3JL2WlTJ8rmDo36IHC7bpMf7JMiQpV14FCdYAMskWyCq44c=
  app: dry-brushlands-5415
  on:
    repo: danielfs/node-app
